# Numpy Arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2], [3,4], [5,6]], np.int64)

In [3]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int64)

In [4]:
np.shape(arr)

(3, 2)

In [5]:
arr.shape

(3, 2)

In [6]:
arr[2].shape

(2,)

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr[2].dtype

dtype('int64')

In [9]:
arr2 = np.array([1, True, "Jonny"])

In [10]:
arr2.dtype

dtype('<U11')

# Array creation Method

### From other Data Structures

#### array function

In [11]:
arr = np.array([1,2,3,4,5], dtype='float32')

In [12]:
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [13]:
arr = np.array([1,2,3,4,5], np.float32)

In [14]:
arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [15]:
dict = {
    1: 'a',
    2: 'b',
    3: 'c'
}
arr_from_dict = np.array(dict.keys())

In [16]:
arr_from_dict

array(dict_keys([1, 2, 3]), dtype=object)

In [17]:
np.array({1,2,3,4,5}, dtype='object') # There is no " np.dtype " attribute

array({1, 2, 3, 4, 5}, dtype=object)

### Intrinsic Array creation methods

In [18]:
arr_zeros = np.zeros((2,3), dtype='int8') # Bydefault dtype = float64

In [19]:
arr_zeros

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [20]:
arr_ones = np.ones((3,2), dtype='int8') # Bydefault dtype = float64

In [21]:
arr_ones

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

#### arange function

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(1, 11, dtype='int8')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [24]:
np.arange(1,2.1,0.3, dtype='int32')

array([1, 1, 1, 1])

#### linspace function

In [25]:
arr = np.linspace(1,5,5)

In [26]:
arr.dtype

dtype('float64')

In [27]:
arr

array([1., 2., 3., 4., 5.])

## Some Other Array Function

In [28]:
arr = np.array([[1,2], [3,4], [5,6]], np.int32)

In [29]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
arr_empty = np.empty((3,3)) # Created an array having random float64 values

In [31]:
arr_empty

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
arr_empty_like = np.empty_like(arr)

In [33]:
arr_empty_like

array([[-651107136,        554],
       [         0,          0],
       [    131074,          0]])

In [34]:
identity_arr = np.identity((3))

In [35]:
identity_arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
arr.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr.reshape((2,3)).ravel()

array([1, 2, 3, 4, 5, 6])

In [39]:
arr.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

# Numpy Axis

In [40]:
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
arr.sum(axis=1)

array([ 3,  7, 11])

In [42]:
arr.sum(axis=0)

array([ 9, 12])

In [43]:
# Some doubt
arr1 = np.array([[1,2], [3,4], [5,6]])
arr2 = np.array([[1, 2], [3,4]])
arr1 + arr2
# ValueError: operands could not be broadcast together with shapes (3,2) (2,2) -> The no. ROWS must be same for performing any operation bewtween two arrays/matrix

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [ ]:
arr

In [ ]:
arr.transpose()

In [ ]:
arr.T

In [ ]:
i = arr.flat # provides an iterator which gives all the elements in a matrix

In [ ]:
for itr in i:
    print(itr)

In [ ]:
print(arr.ndim)
print(arr.size)
print(arr.nbytes) # dtype - int32 -> size(int) = 4 bytes | int64 -> size(int) = 8

In [ ]:
print(arr.argmax()) # Returns the value

# Returns and indices
print(arr.argmax(axis=0))
print(arr.argmax(axis=1))

In [ ]:
print(arr.argmin()) # Returns the value

# Returns and indices
print(arr.argmin(axis=0))
print(arr.argmin(axis=1))

In [ ]:
arr.argsort()

In [ ]:
arr.argsort(axis=1)

In [ ]:
arr.argsort(axis=0)

# Matrix Operations

In [50]:
arr1 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2 = np.array([[1,2,3]])

In [51]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [58]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([3])
arr1 // arr2 # Floor division

array([0, 0, 1, 1])

In [60]:
print(arr.sum())
print(arr.sum(axis=0))
print(arr.sum(axis=1))

21
[ 9 12]
[ 3  7 11]


In [61]:
print(arr.min())
print(arr.min(axis=0))
print(arr.min(axis=1))

1
[1 2]
[1 3 5]


In [62]:
print(arr.max())
print(arr.max(axis=0))
print(arr.max(axis=1))

6
[5 6]
[2 4 6]


In [66]:
np.sqrt(arr)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [68]:
np.where(arr < 3)

(array([0, 0], dtype=int64), array([0, 1], dtype=int64))

In [69]:
np.nonzero(arr)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 0, 1, 0, 1], dtype=int64))

In [70]:
np.count_nonzero(arr)

6

# How numpy arrays are more MEMORY EFFICIENT than python list

In [79]:
import sys
l = [1,2,3]
a = np.array(l, dtype='int64')
print(sys.getsizeof(l[0]) * len(l))
print(a.itemsize * a.size)

84
24
